name: Compile & Compress - Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Generate SemVer
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        patchAll: true
        noVersionBumpBehavior: 'current'

    - name: Update build number in .iss file
      run: |
        sed -i "s/^#define MyAppVersion .*/#define MyAppVersion \"${{ steps.semver.outputs.nextStrict }}\"/" SatMonitor-build.iss
      shell: bash

    - name: Build executable
      run: |
        pyinstaller Sat-Monitor.spec

    - name: Build installer file
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "SatMonitor-build.iss"
      shell: cmd
    
    - name: Upload compiled installer
      uses: actions/upload-artifact@v2
      with:
        name: Sat-Monitor-${{ steps.semver.outputs.nextStrict }}-windows-x86-64.exe
        path: exe/Sat-Monitor-windows-x86-64.exe
  
    - name: Create draft release with artifact
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'Sat-Monitor-${{ steps.semver.outputs.nextStrict }}-windows-x86-64.exe'
        tag: ${{ steps.semver.outputs.nextStrict }}
        makeLatest: true
        draft: true
        prerelease: false
