name: Compile & Compress - Windows

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  compile:
    needs: setup
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        $BUILD_NUMBER = $env:BUILD_NUMBER
        pyinstaller Sat-Monitor.spec

  setup-file:
    needs: compile
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build setup file
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "SatMonitor-build.iss"
      shell: cmd

  upload:
    needs: setup-file
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-installer
        path: exe
