name: Compile & Compress - Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

    - name: Build with PyInstaller
      run: |
        BUILD_NUMBER=$(echo ${{ steps.timestamp.outputs.timestamp }})
        pyinstaller --noconsole --onefile --name "Sat-Monitor-$BUILD_NUMBER" --add-data="src/GUI/Ribbon/icons;GUI/Ribbon/icons" --add-data="src/GUI/Ribbon/stylesheets;GUI/Ribbon/stylesheets" src/main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-executable
        path: dist
